version: 2.0
jobs:

  unittests:
    working_directory: ~/repo
    docker:
    - image: tiangolo/uvicorn-gunicorn-fastapi:python3.7
    steps:
    - checkout
    - run:
        name: Install dependencies
        command: |
          pip install -r test-requirements.txt
    - run:
        name: Run unit tests
        command: |
          export PYTHONPATH=${PYTHONPATH}:$(pwd)
          export ENV=test
          pytest tests/*.py

workflows:
  version: 2
  test-build-deploy:
    jobs:
    - unittests:
        filters:
          branches:
            ignore:
            - master